### Linear regression using numpy

In [2]:
import numpy as np

In [1]:
# f = w*x , dont care about bias
# let w =2
# f = 2*x


In [6]:
X = np.array([1,2,3,4], dtype = np.float32)
Y = np.array([2,4,6,8],dtype=np.float32)
w = 0.0
print(X,Y,w)

[1. 2. 3. 4.] [2. 4. 6. 8.] 0.0


In [7]:
# model prediction
def forward(x):
    return w*x

# loss - MSE
def loss(y,y_predicted):
    return ((y_predicted -y)**2).mean()

# gradient
# MSE = 1/N * (w*x -y)**2
# dMSE/dw = 1/N * (2 *(w*x -y)) * (x)  = 1/N * 2x * (w*x -y)

def gradient(x,y,y_predicted):
    return np.dot(2*x , y_predicted-y).mean()


In [8]:
print(f'pred before taining : f(5) = {forward(x)}')

pred before taining : f(5) = [0. 0. 0. 0.]


In [18]:
# training 
lr =  0.01
n_iters = 10 
#w = 0.0
w = 1.0

for epoch in range(n_iters):
    # forward pass  - prediction
    y_pred = forward(X)
    
    #loss
    l = loss(Y, y_pred)
    print(f'loss after epoch :{epoch} = {l}')
    # gradients 
    dw = gradient(X,Y,y_pred)
    
    # update the weights
    w = w -  (lr * dw)
    #print(w)
    

loss after epoch :0 = 7.5
loss after epoch :1 = 1.1999998092651367
loss after epoch :2 = 0.19199994206428528
loss after epoch :3 = 0.030719999223947525
loss after epoch :4 = 0.004915233701467514
loss after epoch :5 = 0.0007864237995818257
loss after epoch :6 = 0.000125831036712043
loss after epoch :7 = 2.0132965801167302e-05
loss after epoch :8 = 3.220688540750416e-06
loss after epoch :9 = 5.153382858225086e-07


In [19]:
y_pred

array([1.9997379, 3.9994757, 5.9992137, 7.9989514], dtype=float32)

In [20]:
y

array([2., 4., 6., 8.], dtype=float32)

In [21]:
l

5.153383e-07

In [22]:
forward(100)

199.98951125144958